name: Dependabot Review & Merge

on:
  workflow_run:
    workflows: [Dependabot Review]
    types: [completed]
    branches: [security-updates]

permissions:
  contents: write

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.conclusion == 'success' && github.actor == 'dependabot[bot]'}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        # run: gh pr merge --auto --squash "${{ github.event.workflow_run.pull_requests[0].number }}"
        # env:
        #   PR_URL: ${{ github.event.workflow_run.pull_requests[0].url }}
        #   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
